version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: collab_pg
    restart: always
    env_file:
      - ./server/.env
    ports:
      - '5438:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
